apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: ipa2025-msapp-worker-scaler
  namespace: ipa2025
spec:
  scaleTargetRef:
    kind: Deployment
    name: ipa2025-msapp-worker
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: rabbitmq
    metadata:
      protocol: amqp
      queueName: router_jobs
      mode: QueueLength
      value: "10"
      hostFromEnv: RABBITMQ_CONN
